import pygame

storm = pygame.image.load("Assets/Bez-nazwy (1).jpg")
player = pygame.image.load("Assets/ludzik.png")
chest = pygame.image.load("Assets/Tiles/Chest.jpeg")
grass = pygame.image.load("Assets/Tiles/Trawa.jpg")
grass2 = pygame.image.load("Assets/Tiles/Trawa3.jpg")

water = pygame.image.load("Assets/Tiles/Woda.jpg")
gun = pygame.image.load("Assets/Weapons/gun.png")
damagedplayer = pygame.image.load("Assets/damagedplayer.png")
tree1=pygame.image.load("Assets/Tiles/dzewa.jpg")
tree2=pygame.image.load("Assets/Tiles/dzewa2.jpg")
tree3=pygame.image.load("Assets/Tiles/dzewa3.jpg")
mine = pygame.image.load("Assets/Tiles/Kopalnia.jpg")
sand = pygame.image.load("Assets/Tiles/piasek.jpg")
glock17 = pygame.image.load("Assets/Weapons/Glock-18.png")
pump_action_shotgun = pygame.image.load("Assets/Weapons/PumpAhhShotgun.png")
ammo_box = pygame.image.load("Assets/Weapons/AmmoBox.png")
m4a1 = pygame.image.load("Assets/Weapons/M4A1.png")
bolt_action_sniper = pygame.image.load("Assets/Weapons/BoltAction.png")
ammo_crate = pygame.image.load("Assets/Weapons/AmmoCrate.png")
mac10 = pygame.image.load("Assets/Weapons/MAc-10.png")
m1911 = pygame.image.load("Assets/Weapons/Colt45.png")
scarh = pygame.image.load("Assets/Weapons/ScarH.png")
desert_eagle = pygame.image.load("Assets/Weapons/Deagle.png")
magnum44 = pygame.image.load("Assets/Weapons/.44Magnum.png")
gem=pygame.image.load("Assets/Krysztalek.png")
wood=pygame.image.load("Assets/wood.png")

chest_open = pygame.image.load("Assets/Tiles/Chest_Open.png")
chest_closed = pygame.image.load("Assets/Tiles/Chest_Closed.png")
tree_farm=pygame.image.load("Assets/Tiles/dzewa2Mining.png")
mine_farm=pygame.image.load("Assets/Tiles/KopalniaMining.png")
food=pygame.image.load("Assets/Japko.png")
wood_planks=pygame.image.load("Assets/WoodPlanks.png")
wood_planks1=pygame.image.load("Assets/WoodPlanks1.png")
wood_planks2=pygame.image.load("Assets/WoodPlanks2.png")
wood_planks3=pygame.image.load("Assets/WoodPlanks3.png")

zombiee = pygame.image.load("Assets/zombie.png")
